// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fix.proto

#ifndef PROTOBUF_fix_2eproto__INCLUDED
#define PROTOBUF_fix_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "google/protobuf/descriptor.pb.h"
// @@protoc_insertion_point(includes)

namespace fix {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_fix_2eproto();
void protobuf_AssignDesc_fix_2eproto();
void protobuf_ShutdownFile_fix_2eproto();

class Tenor;

enum Datatype {
  CHAR = 0,
  DATA = 1,
  FLOAT = 2,
  INT = 3,
  DAY_OF_MONTH = 4,
  MONTH_YEAR = 5,
  AMT = 6,
  BOOLEAN = 7,
  CURRENCY = 8,
  EXCHANGE = 9,
  LOCAL_MKT_DATE = 10,
  MULTIPLE_STRING_VALUE = 11,
  PRICE = 12,
  PRICE_OFFSET = 13,
  QTY = 14,
  STRING = 15,
  UTC_TIME_ONLY = 16,
  UTC_TIMESTAMP = 17,
  LENGTH = 18,
  NUM_IN_GROUP = 19,
  PERCENTAGE = 20,
  SEQ_NUM = 21,
  TAG_NUM = 22,
  COUNTRY = 23,
  MULTIPLE_CHAR_VALUE = 24,
  PATTERN = 25,
  RESERVED1000PLUS = 26,
  RESERVED100PLUS = 27,
  RESERVED4000PLUS = 28,
  TZ_TIME_ONLY = 29,
  TZ_TIMESTAMP = 30,
  TENOR = 31,
  UTC_DATE_ONLY = 32,
  XML_DATA = 33,
  LANGUAGE = 34
};
bool Datatype_IsValid(int value);
const Datatype Datatype_MIN = CHAR;
const Datatype Datatype_MAX = LANGUAGE;
const int Datatype_ARRAYSIZE = Datatype_MAX + 1;

const ::google::protobuf::EnumDescriptor* Datatype_descriptor();
inline const ::std::string& Datatype_Name(Datatype value) {
  return ::google::protobuf::internal::NameOfEnum(
    Datatype_descriptor(), value);
}
inline bool Datatype_Parse(
    const ::std::string& name, Datatype* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Datatype>(
    Datatype_descriptor(), name, value);
}
enum Version {
  FIX_2_7 = 0,
  FIX_3_0 = 1,
  FIX_4_0 = 2,
  FIX_4_1 = 3,
  FIX_4_2 = 4,
  FIX_4_3 = 5,
  FIX_4_4 = 6,
  FIX_5_0 = 7,
  FIXT_1_1 = 8,
  FIX_5_0_SP_1 = 9,
  FIX_5_0_SP_2 = 10
};
bool Version_IsValid(int value);
const Version Version_MIN = FIX_2_7;
const Version Version_MAX = FIX_5_0_SP_2;
const int Version_ARRAYSIZE = Version_MAX + 1;

const ::google::protobuf::EnumDescriptor* Version_descriptor();
inline const ::std::string& Version_Name(Version value) {
  return ::google::protobuf::internal::NameOfEnum(
    Version_descriptor(), value);
}
inline bool Version_Parse(
    const ::std::string& name, Version* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Version>(
    Version_descriptor(), name, value);
}
// ===================================================================

class Tenor : public ::google::protobuf::Message {
 public:
  Tenor();
  virtual ~Tenor();

  Tenor(const Tenor& from);

  inline Tenor& operator=(const Tenor& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Tenor& default_instance();

  void Swap(Tenor* other);

  // implements Message ----------------------------------------------

  Tenor* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Tenor& from);
  void MergeFrom(const Tenor& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 days = 1;
  inline bool has_days() const;
  inline void clear_days();
  static const int kDaysFieldNumber = 1;
  inline ::google::protobuf::uint32 days() const;
  inline void set_days(::google::protobuf::uint32 value);

  // optional uint32 weeks = 2;
  inline bool has_weeks() const;
  inline void clear_weeks();
  static const int kWeeksFieldNumber = 2;
  inline ::google::protobuf::uint32 weeks() const;
  inline void set_weeks(::google::protobuf::uint32 value);

  // optional uint32 months = 3;
  inline bool has_months() const;
  inline void clear_months();
  static const int kMonthsFieldNumber = 3;
  inline ::google::protobuf::uint32 months() const;
  inline void set_months(::google::protobuf::uint32 value);

  // optional uint32 years = 4;
  inline bool has_years() const;
  inline void clear_years();
  static const int kYearsFieldNumber = 4;
  inline ::google::protobuf::uint32 years() const;
  inline void set_years(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:fix.Tenor)
 private:
  inline void set_has_days();
  inline void clear_has_days();
  inline void set_has_weeks();
  inline void clear_has_weeks();
  inline void set_has_months();
  inline void clear_has_months();
  inline void set_has_years();
  inline void clear_has_years();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 days_;
  ::google::protobuf::uint32 weeks_;
  ::google::protobuf::uint32 months_;
  ::google::protobuf::uint32 years_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_fix_2eproto();
  friend void protobuf_AssignDesc_fix_2eproto();
  friend void protobuf_ShutdownFile_fix_2eproto();

  void InitAsDefaultInstance();
  static Tenor* default_instance_;
};
// ===================================================================

static const int kCategoryFieldNumber = 53002;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  category;
static const int kMsgTypeFieldNumber = 55001;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  msg_type;
static const int kTagFieldNumber = 56003;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::uint32 >, 7, false >
  tag;
static const int kTypeFieldNumber = 56004;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::fix::Datatype, ::fix::Datatype_IsValid>, 14, false >
  type;
static const int kFieldAddedFieldNumber = 56005;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::fix::Version, ::fix::Version_IsValid>, 14, false >
  field_added;
static const int kFieldAddedEpFieldNumber = 56006;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 15, false >
  field_added_ep;
static const int kFieldDeprecatedFieldNumber = 56007;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::fix::Version, ::fix::Version_IsValid>, 14, false >
  field_deprecated;
static const int kEnumValueFieldNumber = 72004;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  enum_value;
static const int kEnumAddedFieldNumber = 72005;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::fix::Version, ::fix::Version_IsValid>, 14, false >
  enum_added;
static const int kEnumAddedEpFieldNumber = 72006;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 15, false >
  enum_added_ep;
static const int kEnumDeprecatedFieldNumber = 72007;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::fix::Version, ::fix::Version_IsValid>, 14, false >
  enum_deprecated;

// ===================================================================

// Tenor

// optional uint32 days = 1;
inline bool Tenor::has_days() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Tenor::set_has_days() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Tenor::clear_has_days() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Tenor::clear_days() {
  days_ = 0u;
  clear_has_days();
}
inline ::google::protobuf::uint32 Tenor::days() const {
  return days_;
}
inline void Tenor::set_days(::google::protobuf::uint32 value) {
  set_has_days();
  days_ = value;
}

// optional uint32 weeks = 2;
inline bool Tenor::has_weeks() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Tenor::set_has_weeks() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Tenor::clear_has_weeks() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Tenor::clear_weeks() {
  weeks_ = 0u;
  clear_has_weeks();
}
inline ::google::protobuf::uint32 Tenor::weeks() const {
  return weeks_;
}
inline void Tenor::set_weeks(::google::protobuf::uint32 value) {
  set_has_weeks();
  weeks_ = value;
}

// optional uint32 months = 3;
inline bool Tenor::has_months() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Tenor::set_has_months() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Tenor::clear_has_months() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Tenor::clear_months() {
  months_ = 0u;
  clear_has_months();
}
inline ::google::protobuf::uint32 Tenor::months() const {
  return months_;
}
inline void Tenor::set_months(::google::protobuf::uint32 value) {
  set_has_months();
  months_ = value;
}

// optional uint32 years = 4;
inline bool Tenor::has_years() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Tenor::set_has_years() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Tenor::clear_has_years() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Tenor::clear_years() {
  years_ = 0u;
  clear_has_years();
}
inline ::google::protobuf::uint32 Tenor::years() const {
  return years_;
}
inline void Tenor::set_years(::google::protobuf::uint32 value) {
  set_has_years();
  years_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace fix

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::fix::Datatype>() {
  return ::fix::Datatype_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::fix::Version>() {
  return ::fix::Version_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_fix_2eproto__INCLUDED
