#Object('main.cpp')
src_files = 'LSETradingAdapter.cpp LSEMessageMapper.cpp'
lib_files = 'Metal pthread xml2 z'
include_path = '../../quickfix/include'
output_file = 'AdapterLSE.so'
#output_file = 'bronze'
cpp_flags='-Wall -std=c++11 -fPIC -fexceptions -O3'

env = Environment()
env.Append( CPPPATH=Split( include_path))
env.Append( CPPFLAGS=Split( cpp_flags))

# Produce the executable
env.Library( output_file, Split( src_files), LIBS=Split(lib_files), LIBPATH='../../../lib');
