#Object('main.cpp')
src_files = 'TradingAdapter.cpp Translator.cpp MessageMapper.cpp'
lib_files = 'pthread xml2 z'
include_path = '../quickfix/include'
output_file = 'Metal.so'
#output_file = 'bronze'
cpp_flags='-Wall -std=c++11 -fPIC -fexceptions -finline-functions'

env = Environment()
env.Append( CPPPATH=Split( include_path))
env.Append( CPPFLAGS=Split( cpp_flags))

# Produce the executable
env.Library( output_file, Split( src_files), LIBS=Split(lib_files), LIBPATH='../../lib');

