// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fix.proto

package org.fixprotocol.components;

public final class Fix {
  private Fix() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(org.fixprotocol.components.Fix.category);
    registry.add(org.fixprotocol.components.Fix.msgType);
    registry.add(org.fixprotocol.components.Fix.tag);
    registry.add(org.fixprotocol.components.Fix.type);
    registry.add(org.fixprotocol.components.Fix.fieldAdded);
    registry.add(org.fixprotocol.components.Fix.fieldAddedEp);
    registry.add(org.fixprotocol.components.Fix.fieldDeprecated);
    registry.add(org.fixprotocol.components.Fix.enumValue);
    registry.add(org.fixprotocol.components.Fix.enumAdded);
    registry.add(org.fixprotocol.components.Fix.enumAddedEp);
    registry.add(org.fixprotocol.components.Fix.enumDeprecated);
  }
  /**
   * Protobuf enum {@code fix.Datatype}
   */
  public enum Datatype
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CHAR = 0;</code>
     */
    CHAR(0, 0),
    /**
     * <code>DATA = 1;</code>
     */
    DATA(1, 1),
    /**
     * <code>FLOAT = 2;</code>
     */
    FLOAT(2, 2),
    /**
     * <code>INT = 3;</code>
     */
    INT(3, 3),
    /**
     * <code>DAY_OF_MONTH = 4;</code>
     */
    DAY_OF_MONTH(4, 4),
    /**
     * <code>MONTH_YEAR = 5;</code>
     */
    MONTH_YEAR(5, 5),
    /**
     * <code>AMT = 6;</code>
     */
    AMT(6, 6),
    /**
     * <code>BOOLEAN = 7;</code>
     */
    BOOLEAN(7, 7),
    /**
     * <code>CURRENCY = 8;</code>
     */
    CURRENCY(8, 8),
    /**
     * <code>EXCHANGE = 9;</code>
     */
    EXCHANGE(9, 9),
    /**
     * <code>LOCAL_MKT_DATE = 10;</code>
     */
    LOCAL_MKT_DATE(10, 10),
    /**
     * <code>MULTIPLE_STRING_VALUE = 11;</code>
     */
    MULTIPLE_STRING_VALUE(11, 11),
    /**
     * <code>PRICE = 12;</code>
     */
    PRICE(12, 12),
    /**
     * <code>PRICE_OFFSET = 13;</code>
     */
    PRICE_OFFSET(13, 13),
    /**
     * <code>QTY = 14;</code>
     */
    QTY(14, 14),
    /**
     * <code>STRING = 15;</code>
     */
    STRING(15, 15),
    /**
     * <code>UTC_TIME_ONLY = 16;</code>
     */
    UTC_TIME_ONLY(16, 16),
    /**
     * <code>UTC_TIMESTAMP = 17;</code>
     */
    UTC_TIMESTAMP(17, 17),
    /**
     * <code>LENGTH = 18;</code>
     */
    LENGTH(18, 18),
    /**
     * <code>NUM_IN_GROUP = 19;</code>
     */
    NUM_IN_GROUP(19, 19),
    /**
     * <code>PERCENTAGE = 20;</code>
     */
    PERCENTAGE(20, 20),
    /**
     * <code>SEQ_NUM = 21;</code>
     */
    SEQ_NUM(21, 21),
    /**
     * <code>TAG_NUM = 22;</code>
     */
    TAG_NUM(22, 22),
    /**
     * <code>COUNTRY = 23;</code>
     */
    COUNTRY(23, 23),
    /**
     * <code>MULTIPLE_CHAR_VALUE = 24;</code>
     */
    MULTIPLE_CHAR_VALUE(24, 24),
    /**
     * <code>PATTERN = 25;</code>
     */
    PATTERN(25, 25),
    /**
     * <code>RESERVED1000PLUS = 26;</code>
     */
    RESERVED1000PLUS(26, 26),
    /**
     * <code>RESERVED100PLUS = 27;</code>
     */
    RESERVED100PLUS(27, 27),
    /**
     * <code>RESERVED4000PLUS = 28;</code>
     */
    RESERVED4000PLUS(28, 28),
    /**
     * <code>TZ_TIME_ONLY = 29;</code>
     */
    TZ_TIME_ONLY(29, 29),
    /**
     * <code>TZ_TIMESTAMP = 30;</code>
     */
    TZ_TIMESTAMP(30, 30),
    /**
     * <code>TENOR = 31;</code>
     */
    TENOR(31, 31),
    /**
     * <code>UTC_DATE_ONLY = 32;</code>
     */
    UTC_DATE_ONLY(32, 32),
    /**
     * <code>XML_DATA = 33;</code>
     */
    XML_DATA(33, 33),
    /**
     * <code>LANGUAGE = 34;</code>
     */
    LANGUAGE(34, 34),
    ;

    /**
     * <code>CHAR = 0;</code>
     */
    public static final int CHAR_VALUE = 0;
    /**
     * <code>DATA = 1;</code>
     */
    public static final int DATA_VALUE = 1;
    /**
     * <code>FLOAT = 2;</code>
     */
    public static final int FLOAT_VALUE = 2;
    /**
     * <code>INT = 3;</code>
     */
    public static final int INT_VALUE = 3;
    /**
     * <code>DAY_OF_MONTH = 4;</code>
     */
    public static final int DAY_OF_MONTH_VALUE = 4;
    /**
     * <code>MONTH_YEAR = 5;</code>
     */
    public static final int MONTH_YEAR_VALUE = 5;
    /**
     * <code>AMT = 6;</code>
     */
    public static final int AMT_VALUE = 6;
    /**
     * <code>BOOLEAN = 7;</code>
     */
    public static final int BOOLEAN_VALUE = 7;
    /**
     * <code>CURRENCY = 8;</code>
     */
    public static final int CURRENCY_VALUE = 8;
    /**
     * <code>EXCHANGE = 9;</code>
     */
    public static final int EXCHANGE_VALUE = 9;
    /**
     * <code>LOCAL_MKT_DATE = 10;</code>
     */
    public static final int LOCAL_MKT_DATE_VALUE = 10;
    /**
     * <code>MULTIPLE_STRING_VALUE = 11;</code>
     */
    public static final int MULTIPLE_STRING_VALUE_VALUE = 11;
    /**
     * <code>PRICE = 12;</code>
     */
    public static final int PRICE_VALUE = 12;
    /**
     * <code>PRICE_OFFSET = 13;</code>
     */
    public static final int PRICE_OFFSET_VALUE = 13;
    /**
     * <code>QTY = 14;</code>
     */
    public static final int QTY_VALUE = 14;
    /**
     * <code>STRING = 15;</code>
     */
    public static final int STRING_VALUE = 15;
    /**
     * <code>UTC_TIME_ONLY = 16;</code>
     */
    public static final int UTC_TIME_ONLY_VALUE = 16;
    /**
     * <code>UTC_TIMESTAMP = 17;</code>
     */
    public static final int UTC_TIMESTAMP_VALUE = 17;
    /**
     * <code>LENGTH = 18;</code>
     */
    public static final int LENGTH_VALUE = 18;
    /**
     * <code>NUM_IN_GROUP = 19;</code>
     */
    public static final int NUM_IN_GROUP_VALUE = 19;
    /**
     * <code>PERCENTAGE = 20;</code>
     */
    public static final int PERCENTAGE_VALUE = 20;
    /**
     * <code>SEQ_NUM = 21;</code>
     */
    public static final int SEQ_NUM_VALUE = 21;
    /**
     * <code>TAG_NUM = 22;</code>
     */
    public static final int TAG_NUM_VALUE = 22;
    /**
     * <code>COUNTRY = 23;</code>
     */
    public static final int COUNTRY_VALUE = 23;
    /**
     * <code>MULTIPLE_CHAR_VALUE = 24;</code>
     */
    public static final int MULTIPLE_CHAR_VALUE_VALUE = 24;
    /**
     * <code>PATTERN = 25;</code>
     */
    public static final int PATTERN_VALUE = 25;
    /**
     * <code>RESERVED1000PLUS = 26;</code>
     */
    public static final int RESERVED1000PLUS_VALUE = 26;
    /**
     * <code>RESERVED100PLUS = 27;</code>
     */
    public static final int RESERVED100PLUS_VALUE = 27;
    /**
     * <code>RESERVED4000PLUS = 28;</code>
     */
    public static final int RESERVED4000PLUS_VALUE = 28;
    /**
     * <code>TZ_TIME_ONLY = 29;</code>
     */
    public static final int TZ_TIME_ONLY_VALUE = 29;
    /**
     * <code>TZ_TIMESTAMP = 30;</code>
     */
    public static final int TZ_TIMESTAMP_VALUE = 30;
    /**
     * <code>TENOR = 31;</code>
     */
    public static final int TENOR_VALUE = 31;
    /**
     * <code>UTC_DATE_ONLY = 32;</code>
     */
    public static final int UTC_DATE_ONLY_VALUE = 32;
    /**
     * <code>XML_DATA = 33;</code>
     */
    public static final int XML_DATA_VALUE = 33;
    /**
     * <code>LANGUAGE = 34;</code>
     */
    public static final int LANGUAGE_VALUE = 34;


    public final int getNumber() { return value; }

    public static Datatype valueOf(int value) {
      switch (value) {
        case 0: return CHAR;
        case 1: return DATA;
        case 2: return FLOAT;
        case 3: return INT;
        case 4: return DAY_OF_MONTH;
        case 5: return MONTH_YEAR;
        case 6: return AMT;
        case 7: return BOOLEAN;
        case 8: return CURRENCY;
        case 9: return EXCHANGE;
        case 10: return LOCAL_MKT_DATE;
        case 11: return MULTIPLE_STRING_VALUE;
        case 12: return PRICE;
        case 13: return PRICE_OFFSET;
        case 14: return QTY;
        case 15: return STRING;
        case 16: return UTC_TIME_ONLY;
        case 17: return UTC_TIMESTAMP;
        case 18: return LENGTH;
        case 19: return NUM_IN_GROUP;
        case 20: return PERCENTAGE;
        case 21: return SEQ_NUM;
        case 22: return TAG_NUM;
        case 23: return COUNTRY;
        case 24: return MULTIPLE_CHAR_VALUE;
        case 25: return PATTERN;
        case 26: return RESERVED1000PLUS;
        case 27: return RESERVED100PLUS;
        case 28: return RESERVED4000PLUS;
        case 29: return TZ_TIME_ONLY;
        case 30: return TZ_TIMESTAMP;
        case 31: return TENOR;
        case 32: return UTC_DATE_ONLY;
        case 33: return XML_DATA;
        case 34: return LANGUAGE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Datatype>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Datatype>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Datatype>() {
            public Datatype findValueByNumber(int number) {
              return Datatype.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.fixprotocol.components.Fix.getDescriptor().getEnumTypes().get(0);
    }

    private static final Datatype[] VALUES = values();

    public static Datatype valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Datatype(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:fix.Datatype)
  }

  /**
   * Protobuf enum {@code fix.Version}
   */
  public enum Version
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FIX_2_7 = 0;</code>
     */
    FIX_2_7(0, 0),
    /**
     * <code>FIX_3_0 = 1;</code>
     */
    FIX_3_0(1, 1),
    /**
     * <code>FIX_4_0 = 2;</code>
     */
    FIX_4_0(2, 2),
    /**
     * <code>FIX_4_1 = 3;</code>
     */
    FIX_4_1(3, 3),
    /**
     * <code>FIX_4_2 = 4;</code>
     */
    FIX_4_2(4, 4),
    /**
     * <code>FIX_4_3 = 5;</code>
     */
    FIX_4_3(5, 5),
    /**
     * <code>FIX_4_4 = 6;</code>
     */
    FIX_4_4(6, 6),
    /**
     * <code>FIX_5_0 = 7;</code>
     */
    FIX_5_0(7, 7),
    /**
     * <code>FIXT_1_1 = 8;</code>
     */
    FIXT_1_1(8, 8),
    /**
     * <code>FIX_5_0_SP_1 = 9;</code>
     */
    FIX_5_0_SP_1(9, 9),
    /**
     * <code>FIX_5_0_SP_2 = 10;</code>
     */
    FIX_5_0_SP_2(10, 10),
    ;

    /**
     * <code>FIX_2_7 = 0;</code>
     */
    public static final int FIX_2_7_VALUE = 0;
    /**
     * <code>FIX_3_0 = 1;</code>
     */
    public static final int FIX_3_0_VALUE = 1;
    /**
     * <code>FIX_4_0 = 2;</code>
     */
    public static final int FIX_4_0_VALUE = 2;
    /**
     * <code>FIX_4_1 = 3;</code>
     */
    public static final int FIX_4_1_VALUE = 3;
    /**
     * <code>FIX_4_2 = 4;</code>
     */
    public static final int FIX_4_2_VALUE = 4;
    /**
     * <code>FIX_4_3 = 5;</code>
     */
    public static final int FIX_4_3_VALUE = 5;
    /**
     * <code>FIX_4_4 = 6;</code>
     */
    public static final int FIX_4_4_VALUE = 6;
    /**
     * <code>FIX_5_0 = 7;</code>
     */
    public static final int FIX_5_0_VALUE = 7;
    /**
     * <code>FIXT_1_1 = 8;</code>
     */
    public static final int FIXT_1_1_VALUE = 8;
    /**
     * <code>FIX_5_0_SP_1 = 9;</code>
     */
    public static final int FIX_5_0_SP_1_VALUE = 9;
    /**
     * <code>FIX_5_0_SP_2 = 10;</code>
     */
    public static final int FIX_5_0_SP_2_VALUE = 10;


    public final int getNumber() { return value; }

    public static Version valueOf(int value) {
      switch (value) {
        case 0: return FIX_2_7;
        case 1: return FIX_3_0;
        case 2: return FIX_4_0;
        case 3: return FIX_4_1;
        case 4: return FIX_4_2;
        case 5: return FIX_4_3;
        case 6: return FIX_4_4;
        case 7: return FIX_5_0;
        case 8: return FIXT_1_1;
        case 9: return FIX_5_0_SP_1;
        case 10: return FIX_5_0_SP_2;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Version>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Version>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Version>() {
            public Version findValueByNumber(int number) {
              return Version.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.fixprotocol.components.Fix.getDescriptor().getEnumTypes().get(1);
    }

    private static final Version[] VALUES = values();

    public static Version valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Version(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:fix.Version)
  }

  public interface TenorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint32 days = 1;
    /**
     * <code>optional uint32 days = 1;</code>
     */
    boolean hasDays();
    /**
     * <code>optional uint32 days = 1;</code>
     */
    int getDays();

    // optional uint32 weeks = 2;
    /**
     * <code>optional uint32 weeks = 2;</code>
     */
    boolean hasWeeks();
    /**
     * <code>optional uint32 weeks = 2;</code>
     */
    int getWeeks();

    // optional uint32 months = 3;
    /**
     * <code>optional uint32 months = 3;</code>
     */
    boolean hasMonths();
    /**
     * <code>optional uint32 months = 3;</code>
     */
    int getMonths();

    // optional uint32 years = 4;
    /**
     * <code>optional uint32 years = 4;</code>
     */
    boolean hasYears();
    /**
     * <code>optional uint32 years = 4;</code>
     */
    int getYears();
  }
  /**
   * Protobuf type {@code fix.Tenor}
   */
  public static final class Tenor extends
      com.google.protobuf.GeneratedMessage
      implements TenorOrBuilder {
    // Use Tenor.newBuilder() to construct.
    private Tenor(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Tenor(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Tenor defaultInstance;
    public static Tenor getDefaultInstance() {
      return defaultInstance;
    }

    public Tenor getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Tenor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              days_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              weeks_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              months_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              years_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.fixprotocol.components.Fix.internal_static_fix_Tenor_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.fixprotocol.components.Fix.internal_static_fix_Tenor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.fixprotocol.components.Fix.Tenor.class, org.fixprotocol.components.Fix.Tenor.Builder.class);
    }

    public static com.google.protobuf.Parser<Tenor> PARSER =
        new com.google.protobuf.AbstractParser<Tenor>() {
      public Tenor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Tenor(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Tenor> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint32 days = 1;
    public static final int DAYS_FIELD_NUMBER = 1;
    private int days_;
    /**
     * <code>optional uint32 days = 1;</code>
     */
    public boolean hasDays() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 days = 1;</code>
     */
    public int getDays() {
      return days_;
    }

    // optional uint32 weeks = 2;
    public static final int WEEKS_FIELD_NUMBER = 2;
    private int weeks_;
    /**
     * <code>optional uint32 weeks = 2;</code>
     */
    public boolean hasWeeks() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 weeks = 2;</code>
     */
    public int getWeeks() {
      return weeks_;
    }

    // optional uint32 months = 3;
    public static final int MONTHS_FIELD_NUMBER = 3;
    private int months_;
    /**
     * <code>optional uint32 months = 3;</code>
     */
    public boolean hasMonths() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 months = 3;</code>
     */
    public int getMonths() {
      return months_;
    }

    // optional uint32 years = 4;
    public static final int YEARS_FIELD_NUMBER = 4;
    private int years_;
    /**
     * <code>optional uint32 years = 4;</code>
     */
    public boolean hasYears() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 years = 4;</code>
     */
    public int getYears() {
      return years_;
    }

    private void initFields() {
      days_ = 0;
      weeks_ = 0;
      months_ = 0;
      years_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, days_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, weeks_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, months_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, years_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, days_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, weeks_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, months_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, years_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.fixprotocol.components.Fix.Tenor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.fixprotocol.components.Fix.Tenor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.fixprotocol.components.Fix.Tenor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.fixprotocol.components.Fix.Tenor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.fixprotocol.components.Fix.Tenor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.fixprotocol.components.Fix.Tenor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.fixprotocol.components.Fix.Tenor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.fixprotocol.components.Fix.Tenor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.fixprotocol.components.Fix.Tenor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.fixprotocol.components.Fix.Tenor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.fixprotocol.components.Fix.Tenor prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fix.Tenor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.fixprotocol.components.Fix.TenorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.fixprotocol.components.Fix.internal_static_fix_Tenor_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.fixprotocol.components.Fix.internal_static_fix_Tenor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.fixprotocol.components.Fix.Tenor.class, org.fixprotocol.components.Fix.Tenor.Builder.class);
      }

      // Construct using org.fixprotocol.components.Fix.Tenor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        days_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        weeks_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        months_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        years_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.fixprotocol.components.Fix.internal_static_fix_Tenor_descriptor;
      }

      public org.fixprotocol.components.Fix.Tenor getDefaultInstanceForType() {
        return org.fixprotocol.components.Fix.Tenor.getDefaultInstance();
      }

      public org.fixprotocol.components.Fix.Tenor build() {
        org.fixprotocol.components.Fix.Tenor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.fixprotocol.components.Fix.Tenor buildPartial() {
        org.fixprotocol.components.Fix.Tenor result = new org.fixprotocol.components.Fix.Tenor(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.days_ = days_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.weeks_ = weeks_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.months_ = months_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.years_ = years_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.fixprotocol.components.Fix.Tenor) {
          return mergeFrom((org.fixprotocol.components.Fix.Tenor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.fixprotocol.components.Fix.Tenor other) {
        if (other == org.fixprotocol.components.Fix.Tenor.getDefaultInstance()) return this;
        if (other.hasDays()) {
          setDays(other.getDays());
        }
        if (other.hasWeeks()) {
          setWeeks(other.getWeeks());
        }
        if (other.hasMonths()) {
          setMonths(other.getMonths());
        }
        if (other.hasYears()) {
          setYears(other.getYears());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.fixprotocol.components.Fix.Tenor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.fixprotocol.components.Fix.Tenor) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint32 days = 1;
      private int days_ ;
      /**
       * <code>optional uint32 days = 1;</code>
       */
      public boolean hasDays() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 days = 1;</code>
       */
      public int getDays() {
        return days_;
      }
      /**
       * <code>optional uint32 days = 1;</code>
       */
      public Builder setDays(int value) {
        bitField0_ |= 0x00000001;
        days_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 days = 1;</code>
       */
      public Builder clearDays() {
        bitField0_ = (bitField0_ & ~0x00000001);
        days_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 weeks = 2;
      private int weeks_ ;
      /**
       * <code>optional uint32 weeks = 2;</code>
       */
      public boolean hasWeeks() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 weeks = 2;</code>
       */
      public int getWeeks() {
        return weeks_;
      }
      /**
       * <code>optional uint32 weeks = 2;</code>
       */
      public Builder setWeeks(int value) {
        bitField0_ |= 0x00000002;
        weeks_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 weeks = 2;</code>
       */
      public Builder clearWeeks() {
        bitField0_ = (bitField0_ & ~0x00000002);
        weeks_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 months = 3;
      private int months_ ;
      /**
       * <code>optional uint32 months = 3;</code>
       */
      public boolean hasMonths() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 months = 3;</code>
       */
      public int getMonths() {
        return months_;
      }
      /**
       * <code>optional uint32 months = 3;</code>
       */
      public Builder setMonths(int value) {
        bitField0_ |= 0x00000004;
        months_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 months = 3;</code>
       */
      public Builder clearMonths() {
        bitField0_ = (bitField0_ & ~0x00000004);
        months_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 years = 4;
      private int years_ ;
      /**
       * <code>optional uint32 years = 4;</code>
       */
      public boolean hasYears() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 years = 4;</code>
       */
      public int getYears() {
        return years_;
      }
      /**
       * <code>optional uint32 years = 4;</code>
       */
      public Builder setYears(int value) {
        bitField0_ |= 0x00000008;
        years_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 years = 4;</code>
       */
      public Builder clearYears() {
        bitField0_ = (bitField0_ & ~0x00000008);
        years_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:fix.Tenor)
    }

    static {
      defaultInstance = new Tenor(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:fix.Tenor)
  }

  public static final int CATEGORY_FIELD_NUMBER = 53002;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.String> category = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int MSG_TYPE_FIELD_NUMBER = 55001;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> msgType = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int TAG_FIELD_NUMBER = 56003;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Integer> tag = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int TYPE_FIELD_NUMBER = 56004;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      org.fixprotocol.components.Fix.Datatype> type = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        org.fixprotocol.components.Fix.Datatype.class,
        null);
  public static final int FIELD_ADDED_FIELD_NUMBER = 56005;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      org.fixprotocol.components.Fix.Version> fieldAdded = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        org.fixprotocol.components.Fix.Version.class,
        null);
  public static final int FIELD_ADDED_EP_FIELD_NUMBER = 56006;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Integer> fieldAddedEp = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int FIELD_DEPRECATED_FIELD_NUMBER = 56007;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      org.fixprotocol.components.Fix.Version> fieldDeprecated = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        org.fixprotocol.components.Fix.Version.class,
        null);
  public static final int ENUM_VALUE_FIELD_NUMBER = 72004;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      java.lang.String> enumValue = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int ENUM_ADDED_FIELD_NUMBER = 72005;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      org.fixprotocol.components.Fix.Version> enumAdded = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        org.fixprotocol.components.Fix.Version.class,
        null);
  public static final int ENUM_ADDED_EP_FIELD_NUMBER = 72006;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      java.lang.Integer> enumAddedEp = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int ENUM_DEPRECATED_FIELD_NUMBER = 72007;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      org.fixprotocol.components.Fix.Version> enumDeprecated = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        org.fixprotocol.components.Fix.Version.class,
        null);
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_fix_Tenor_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fix_Tenor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tfix.proto\022\003fix\032 google/protobuf/descri" +
      "ptor.proto\"C\n\005Tenor\022\014\n\004days\030\001 \001(\r\022\r\n\005wee" +
      "ks\030\002 \001(\r\022\016\n\006months\030\003 \001(\r\022\r\n\005years\030\004 \001(\r*" +
      "\200\006\n\010Datatype\022\016\n\004CHAR\020\000\032\004\250\224#\000\022\016\n\004DATA\020\001\032\004" +
      "\250\224#\000\022\017\n\005FLOAT\020\002\032\004\250\224#\000\022\r\n\003INT\020\003\032\004\250\224#\000\022\026\n\014" +
      "DAY_OF_MONTH\020\004\032\004\250\224#\003\022\024\n\nMONTH_YEAR\020\005\032\004\250\224" +
      "#\003\022\r\n\003AMT\020\006\032\004\250\224#\004\022\021\n\007BOOLEAN\020\007\032\004\250\224#\004\022\022\n\010" +
      "CURRENCY\020\010\032\004\250\224#\004\022\022\n\010EXCHANGE\020\t\032\004\250\224#\004\022\030\n\016" +
      "LOCAL_MKT_DATE\020\n\032\004\250\224#\004\022\037\n\025MULTIPLE_STRIN" +
      "G_VALUE\020\013\032\004\250\224#\004\022\017\n\005PRICE\020\014\032\004\250\224#\004\022\026\n\014PRIC",
      "E_OFFSET\020\r\032\004\250\224#\004\022\r\n\003QTY\020\016\032\004\250\224#\004\022\020\n\006STRIN" +
      "G\020\017\032\004\250\224#\004\022\027\n\rUTC_TIME_ONLY\020\020\032\004\250\224#\004\022\027\n\rUT" +
      "C_TIMESTAMP\020\021\032\004\250\224#\004\022\020\n\006LENGTH\020\022\032\004\250\224#\005\022\026\n" +
      "\014NUM_IN_GROUP\020\023\032\004\250\224#\005\022\024\n\nPERCENTAGE\020\024\032\004\250" +
      "\224#\005\022\021\n\007SEQ_NUM\020\025\032\004\250\224#\005\022\021\n\007TAG_NUM\020\026\032\004\250\224#" +
      "\005\022\021\n\007COUNTRY\020\027\032\004\250\224#\006\022\035\n\023MULTIPLE_CHAR_VA" +
      "LUE\020\030\032\004\250\224#\006\022\021\n\007PATTERN\020\031\032\004\250\224#\006\022\032\n\020RESERV" +
      "ED1000PLUS\020\032\032\004\250\224#\006\022\031\n\017RESERVED100PLUS\020\033\032" +
      "\004\250\224#\006\022\032\n\020RESERVED4000PLUS\020\034\032\004\250\224#\006\022\026\n\014TZ_" +
      "TIME_ONLY\020\035\032\004\250\224#\006\022\026\n\014TZ_TIMESTAMP\020\036\032\004\250\224#",
      "\006\022\017\n\005TENOR\020\037\032\004\250\224#\006\022\027\n\rUTC_DATE_ONLY\020 \032\004\250" +
      "\224#\006\022\022\n\010XML_DATA\020!\032\004\250\224#\007\022\031\n\010LANGUAGE\020\"\032\013\250" +
      "\224#\t\265\224#Z\000\000\000*\243\001\n\007Version\022\013\n\007FIX_2_7\020\000\022\013\n\007F" +
      "IX_3_0\020\001\022\013\n\007FIX_4_0\020\002\022\013\n\007FIX_4_1\020\003\022\013\n\007FI" +
      "X_4_2\020\004\022\013\n\007FIX_4_3\020\005\022\013\n\007FIX_4_4\020\006\022\013\n\007FIX" +
      "_5_0\020\007\022\014\n\010FIXT_1_1\020\010\022\020\n\014FIX_5_0_SP_1\020\t\022\020" +
      "\n\014FIX_5_0_SP_2\020\n:0\n\010category\022\034.google.pr" +
      "otobuf.FileOptions\030\212\236\003 \001(\t:3\n\010msg_type\022\037" +
      ".google.protobuf.MessageOptions\030\331\255\003 \001(\t:" +
      ",\n\003tag\022\035.google.protobuf.FieldOptions\030\303\265",
      "\003 \001(\007:<\n\004type\022\035.google.protobuf.FieldOpt" +
      "ions\030\304\265\003 \001(\0162\r.fix.Datatype:B\n\013field_add" +
      "ed\022\035.google.protobuf.FieldOptions\030\305\265\003 \001(" +
      "\0162\014.fix.Version:7\n\016field_added_ep\022\035.goog" +
      "le.protobuf.FieldOptions\030\306\265\003 \001(\017:G\n\020fiel" +
      "d_deprecated\022\035.google.protobuf.FieldOpti" +
      "ons\030\307\265\003 \001(\0162\014.fix.Version:7\n\nenum_value\022" +
      "!.google.protobuf.EnumValueOptions\030\304\262\004 \001" +
      "(\t:E\n\nenum_added\022!.google.protobuf.EnumV" +
      "alueOptions\030\305\262\004 \001(\0162\014.fix.Version::\n\renu",
      "m_added_ep\022!.google.protobuf.EnumValueOp" +
      "tions\030\306\262\004 \001(\017:J\n\017enum_deprecated\022!.googl" +
      "e.protobuf.EnumValueOptions\030\307\262\004 \001(\0162\014.fi" +
      "x.VersionB!\n\032org.fixprotocol.componentsB" +
      "\003Fix"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_fix_Tenor_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_fix_Tenor_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_fix_Tenor_descriptor,
              new java.lang.String[] { "Days", "Weeks", "Months", "Years", });
          category.internalInit(descriptor.getExtensions().get(0));
          msgType.internalInit(descriptor.getExtensions().get(1));
          tag.internalInit(descriptor.getExtensions().get(2));
          type.internalInit(descriptor.getExtensions().get(3));
          fieldAdded.internalInit(descriptor.getExtensions().get(4));
          fieldAddedEp.internalInit(descriptor.getExtensions().get(5));
          fieldDeprecated.internalInit(descriptor.getExtensions().get(6));
          enumValue.internalInit(descriptor.getExtensions().get(7));
          enumAdded.internalInit(descriptor.getExtensions().get(8));
          enumAddedEp.internalInit(descriptor.getExtensions().get(9));
          enumDeprecated.internalInit(descriptor.getExtensions().get(10));
          com.google.protobuf.ExtensionRegistry registry =
            com.google.protobuf.ExtensionRegistry.newInstance();
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAdded);
          registry.add(org.fixprotocol.components.Fix.enumAddedEp);
          return registry;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
