// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package org.fixprotocol.components;

public final class Meta {
  private Meta() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(org.fixprotocol.components.Meta.timeUnit);
    registry.add(org.fixprotocol.components.Meta.exponent);
    registry.add(org.fixprotocol.components.Meta.minLength);
    registry.add(org.fixprotocol.components.Meta.maxLength);
    registry.add(org.fixprotocol.components.Meta.minValue);
    registry.add(org.fixprotocol.components.Meta.maxValue);
  }
  /**
   * Protobuf enum {@code meta.TimeUnit}
   */
  public enum TimeUnit
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TIME_UNIT_DAYS = 0;</code>
     */
    TIME_UNIT_DAYS(0, 0),
    /**
     * <code>TIME_UNIT_SECONDS = 1;</code>
     */
    TIME_UNIT_SECONDS(1, 1),
    /**
     * <code>TIME_UNIT_MILLISECONDS = 2;</code>
     */
    TIME_UNIT_MILLISECONDS(2, 2),
    /**
     * <code>TIME_UNIT_MICROSECONDS = 3;</code>
     */
    TIME_UNIT_MICROSECONDS(3, 3),
    /**
     * <code>TIME_UNIT_NANOSECONDS = 4;</code>
     */
    TIME_UNIT_NANOSECONDS(4, 4),
    /**
     * <code>TIME_UNIT_PICOSECONDS = 5;</code>
     */
    TIME_UNIT_PICOSECONDS(5, 5),
    ;

    /**
     * <code>TIME_UNIT_DAYS = 0;</code>
     */
    public static final int TIME_UNIT_DAYS_VALUE = 0;
    /**
     * <code>TIME_UNIT_SECONDS = 1;</code>
     */
    public static final int TIME_UNIT_SECONDS_VALUE = 1;
    /**
     * <code>TIME_UNIT_MILLISECONDS = 2;</code>
     */
    public static final int TIME_UNIT_MILLISECONDS_VALUE = 2;
    /**
     * <code>TIME_UNIT_MICROSECONDS = 3;</code>
     */
    public static final int TIME_UNIT_MICROSECONDS_VALUE = 3;
    /**
     * <code>TIME_UNIT_NANOSECONDS = 4;</code>
     */
    public static final int TIME_UNIT_NANOSECONDS_VALUE = 4;
    /**
     * <code>TIME_UNIT_PICOSECONDS = 5;</code>
     */
    public static final int TIME_UNIT_PICOSECONDS_VALUE = 5;


    public final int getNumber() { return value; }

    public static TimeUnit valueOf(int value) {
      switch (value) {
        case 0: return TIME_UNIT_DAYS;
        case 1: return TIME_UNIT_SECONDS;
        case 2: return TIME_UNIT_MILLISECONDS;
        case 3: return TIME_UNIT_MICROSECONDS;
        case 4: return TIME_UNIT_NANOSECONDS;
        case 5: return TIME_UNIT_PICOSECONDS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TimeUnit>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TimeUnit>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TimeUnit>() {
            public TimeUnit findValueByNumber(int number) {
              return TimeUnit.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.fixprotocol.components.Meta.getDescriptor().getEnumTypes().get(0);
    }

    private static final TimeUnit[] VALUES = values();

    public static TimeUnit valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TimeUnit(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:meta.TimeUnit)
  }

  /**
   * Protobuf enum {@code meta.Epoch}
   */
  public enum Epoch
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EPOCH_MIDNIGHT = 0;</code>
     *
     * <pre>
     * For time-only fields, midnight of a given date
     * </pre>
     */
    EPOCH_MIDNIGHT(0, 0),
    /**
     * <code>EPOCH_UNIX = 1;</code>
     *
     * <pre>
     * Midnight of Jan-01 1970
     * </pre>
     */
    EPOCH_UNIX(1, 1),
    /**
     * <code>EPOCH_1900 = 2;</code>
     *
     * <pre>
     * Midnight of Jan-01 1900
     * </pre>
     */
    EPOCH_1900(2, 2),
    /**
     * <code>EPOCH_2000 = 3;</code>
     *
     * <pre>
     * Midnight of Jan-01 2000
     * </pre>
     */
    EPOCH_2000(3, 3),
    ;

    /**
     * <code>EPOCH_MIDNIGHT = 0;</code>
     *
     * <pre>
     * For time-only fields, midnight of a given date
     * </pre>
     */
    public static final int EPOCH_MIDNIGHT_VALUE = 0;
    /**
     * <code>EPOCH_UNIX = 1;</code>
     *
     * <pre>
     * Midnight of Jan-01 1970
     * </pre>
     */
    public static final int EPOCH_UNIX_VALUE = 1;
    /**
     * <code>EPOCH_1900 = 2;</code>
     *
     * <pre>
     * Midnight of Jan-01 1900
     * </pre>
     */
    public static final int EPOCH_1900_VALUE = 2;
    /**
     * <code>EPOCH_2000 = 3;</code>
     *
     * <pre>
     * Midnight of Jan-01 2000
     * </pre>
     */
    public static final int EPOCH_2000_VALUE = 3;


    public final int getNumber() { return value; }

    public static Epoch valueOf(int value) {
      switch (value) {
        case 0: return EPOCH_MIDNIGHT;
        case 1: return EPOCH_UNIX;
        case 2: return EPOCH_1900;
        case 3: return EPOCH_2000;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Epoch>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Epoch>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Epoch>() {
            public Epoch findValueByNumber(int number) {
              return Epoch.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.fixprotocol.components.Meta.getDescriptor().getEnumTypes().get(1);
    }

    private static final Epoch[] VALUES = values();

    public static Epoch valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Epoch(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:meta.Epoch)
  }

  public static final int TIME_UNIT_FIELD_NUMBER = 51001;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      org.fixprotocol.components.Meta.TimeUnit> timeUnit = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        org.fixprotocol.components.Meta.TimeUnit.class,
        null);
  public static final int EXPONENT_FIELD_NUMBER = 51003;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Integer> exponent = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int MIN_LENGTH_FIELD_NUMBER = 51004;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Integer> minLength = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int MAX_LENGTH_FIELD_NUMBER = 51005;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Integer> maxLength = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int MIN_VALUE_FIELD_NUMBER = 51006;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Long> minValue = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Long.class,
        null);
  public static final int MAX_VALUE_FIELD_NUMBER = 51007;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Long> maxValue = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Long.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nmeta.proto\022\004meta\032 google/protobuf/desc" +
      "riptor.proto*\243\001\n\010TimeUnit\022\022\n\016TIME_UNIT_D" +
      "AYS\020\000\022\025\n\021TIME_UNIT_SECONDS\020\001\022\032\n\026TIME_UNI" +
      "T_MILLISECONDS\020\002\022\032\n\026TIME_UNIT_MICROSECON" +
      "DS\020\003\022\031\n\025TIME_UNIT_NANOSECONDS\020\004\022\031\n\025TIME_" +
      "UNIT_PICOSECONDS\020\005*K\n\005Epoch\022\022\n\016EPOCH_MID" +
      "NIGHT\020\000\022\016\n\nEPOCH_UNIX\020\001\022\016\n\nEPOCH_1900\020\002\022" +
      "\016\n\nEPOCH_2000\020\003:B\n\ttime_unit\022\035.google.pr" +
      "otobuf.FieldOptions\030\271\216\003 \001(\0162\016.meta.TimeU" +
      "nit:1\n\010exponent\022\035.google.protobuf.FieldO",
      "ptions\030\273\216\003 \001(\017:3\n\nmin_length\022\035.google.pr" +
      "otobuf.FieldOptions\030\274\216\003 \001(\007:3\n\nmax_lengt" +
      "h\022\035.google.protobuf.FieldOptions\030\275\216\003 \001(\007" +
      ":2\n\tmin_value\022\035.google.protobuf.FieldOpt" +
      "ions\030\276\216\003 \001(\020:2\n\tmax_value\022\035.google.proto" +
      "buf.FieldOptions\030\277\216\003 \001(\020B\"\n\032org.fixproto" +
      "col.componentsB\004Meta"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          timeUnit.internalInit(descriptor.getExtensions().get(0));
          exponent.internalInit(descriptor.getExtensions().get(1));
          minLength.internalInit(descriptor.getExtensions().get(2));
          maxLength.internalInit(descriptor.getExtensions().get(3));
          minValue.internalInit(descriptor.getExtensions().get(4));
          maxValue.internalInit(descriptor.getExtensions().get(5));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
