#Object('main.cpp')
src_files = 'main.cpp parsing.cpp Adapter.cpp'
lib_files = 'Metal quickfix AdapterQuickFIX pthread xml2 z'
include_path = '../../adapters ../../quickfix/include'
output_file = 'bronze'
output_dir = '/home/jc/metal/bin'
#output_file = 'bronze'
cpp_flags='-Wall -std=c++11 -fexceptions -finline-functions'

env = Environment()
env.Append( CPPPATH=Split( include_path))
env.Append( CPPFLAGS=Split( cpp_flags))

# Produce the executable
env.Program( output_file, Split( src_files), LIBS=Split(lib_files), LIBPATH='../../../lib');

env.Install( output_dir, output_file)


