#Object('main.cpp')
src_files = 'main.cpp parsing.cpp MyAdapter.cpp'
lib_files = 'AdapterQuickFIX Metal quickfix pthread xml2 z'
include_path = '../../ ../../quickfix/include'
output_file = 'bronze'
#output_file = 'bronze'
cpp_flags='-Wall -std=c++11 -fexceptions -finline-functions'

env = Environment()
env.Append( CPPPATH=Split( include_path))
env.Append( CPPFLAGS=Split( cpp_flags))

# Produce the executable
env.Program( output_file, Split( src_files), LIBS=Split(lib_files), LIBPATH='../../../lib');
